name: Tag a release
on:
  push:
    paths:
      - package.json
    branches:
      - "master"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tag-if-needed:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Create tag if needed
        run: node scripts/tag.mjs
